# Generated by Django 2.2.6 on 2019-10-02 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
