# Generated by Django 2.2.6 on 2019-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0002_studentdetails_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
