# Generated by Django 2.2.6 on 2019-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0003_auto_20191002_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='teacher_mail_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='teacher_password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
