# Generated by Django 2.2.6 on 2019-10-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0004_auto_20191010_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Data', models.TextField()),
                ('Test_Date', models.DateField()),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schl_app.StudentDetails')),
            ],
        ),
    ]
