# Generated by Django 2.2.6 on 2019-10-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0005_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='Student_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
